# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jonathon Bechtel 
tagline:          'A grad student blog'
description:      'Join me on my journey through the triumphs and tribulations of graduate life.'
url:              http://jonathonbechtel.com
baseurl:          /

author:
  name:           'Jonathon Bechtel'
  url:            jonathonbechtel.com 


paginate:         5
gems: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://jbechtel.github.io
