# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jonathon Bechtel 
tagline:          'A grad student blog'
description:      "Let's learn together"
url:              http://jonathonbechtel.com
baseurl:          /

author:
  gravatar_md5:  783fc5ac9e9762db9407533a116bef93
  name:           'Jonathon Bechtel'
  url:            http://jonathonbechtel.com 
  linkedin:       jonathonbechtel
  github:         jbechtel
  email:          jbechtel91@gmail.com


paginate:         5
gems: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jbechtel/jbechtel.github.io

